# Операції над масивами
> хоча базово всі дані інтерпретуються як масиви, можливо працювавти з двовимірними масивами як алгебраїчними матрицями.

In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

> згенеруємо декілька масивів різними способами та виконаємо базові математичні операції.

In [2]:
import numpy as np

# Задаємо розмірність
l = (3, 3)

# Створення матриць
O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

# Виконання операцій
print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {np.divide(R, C, where=C!=0, out=np.zeros_like(R))} # Уникаємо ділення на 0
Степінь:\n {C ** Z}
Порівняння:\n {R > 0.5}
Ділення на 0:\n {np.divide(O, Z, where=Z!=0, out=np.zeros_like(Z))} # Уникаємо ділення на 0
""")

# Створення матриці
E = np.eye(l[0])
print(f"Матриця eye:\n{E}")
# Порівняння на наявність 1
comparison = E == 1
print(f"Порівняння з 1:\n{comparison}")

# Створення матриць
ones_matrix = np.ones(l)
eye_matrix = np.eye(l[0])
result_matrix = ones_matrix - eye_matrix
print(f"Результуюча матриця (ones - eye):\n{result_matrix}")


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.06876024 0.12467286 0.40917586]
 [0.60258554 0.63530419 0.98174265]
 [0.22697983 0.3590863  0.47462838]]
Ділення:
 [[0.         0.12467286 0.20458793]
 [0.         0.63530419 0.49087132]
 [0.         0.3590863  0.23731419]] # Уникаємо ділення на 0
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Порівняння:
 [[False False False]
 [ True  True  True]
 [False False False]]
Ділення на 0:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] # Уникаємо ділення на 0

Матриця eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Порівняння з 1:
[[ True False False]
 [False  True False]
 [False False  True]]
Результуюча матриця (ones - eye):
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


# Множення матриць
>  якщо маси яно не задати як матрицю, тоді операції будуть виконуавтись до кожного елемента.

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])

print(f"Маємо два масиви:\n{A} \n{B}")

# Поелементне множення
R = A * B
print(f"Тут виконується поелементне множення:\n{R}")

# Множення як матриць
R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n{R}")

# Перетворення на матриці за допомогою np.asmatrix
MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n{R}")


Маємо два масиви:
[[1 2 3]
 [2 2 2]
 [3 3 3]] 
[[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
[[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Вирівнювання розмірностей
> broadcasting - механізм який дозволяє вирівняти розмірність масивів для того щоб здійснити операцію над кожним його елементом. Масиви повинні бути співрозмірні, або один з вимірівв має бути 1 (рядок або стопець).

In [4]:
import numpy as np

A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])

print(f"Маємо два масиви:\n{A} \n{B}")

# Поелементне множення
R = A * B
print(f"Тут виконується поелементне множення:\n{R}")

# Множення як матриць
R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n{R}")

# Перетворення на матриці за допомогою np.asmatrix
MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n{R}")


Маємо два масиви:
[[1 2 3]
 [2 2 2]
 [3 3 3]] 
[[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
[[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Конкатенація, повторення та зміна форми (shape)
> конкатенація (`concatenate`) - процес зчеплення двох і більше елементів (рядків, стовпців), у нашому випадку масивів які мають однакову форму shape;

> повторення (`tile`) - процес побудови масива шляхом повторення заданого елемента;

> зміна форми (`reshape`) або розмірності масива за умови що сумарна розмірність залишиться незмінною;

In [5]:
import numpy as np

# Вихідні дані
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Двовимірний масив 3x3
B = np.random.random((3, 3))  # або B = np.random.random(3) для тесту з одномірним масивом
D = np.ones(3)
Z = np.zeros((3, 1))

# Ініціалізація C (одновимірний масив)
C = np.random.random(3)  # Створимо випадковий одномірний масив для C

# Перетворення одномірного масиву B на двовимірний
if B.ndim == 1:
    B = B[:, np.newaxis]  # Перетворюємо на 2D

# Перетворення C на (3, 1)
C = C[:, np.newaxis]  # З одновимірного (3,) на (3, 1)

# Роздрукуємо результат
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z), axis=1)}
Масив D {D} має розмірність {D.shape}, тому може виконати операцію конкатенації з B {B.shape}:
{np.concatenate((B, D[:, np.newaxis]), axis=1)}
Для конкатенації з C:
{C}
де C має розмірність = {C.shape}, потрібно змінити розмірність D = {D.shape}.
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3, 1)).shape}
В результаті ми можемо виконати конкатенацію:
{np.concatenate((C, D.reshape((3, 1))), axis=1)}
При повторенні D {D} 2 рази для рядків та 3 для стовпців будемо мати:
{np.tile(D, (2, 3))}
Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")

# Homework
# # Створення двовимірного масиву та конкатенація/повторення
arr1 = np.arange(6).reshape(2, 3)
print(f"Двовимірний масив:\n{arr1}")
print(f"Конкатенація (рядки):\n{np.concatenate((arr1, arr1), axis=0)}")
print(f"Конкатенація (стовпці):\n{np.concatenate((arr1, arr1), axis=1)}")
print(f"Повторення:\n{np.tile(arr1, (2, 2))}")
 
# Масив із різною кількістю рядків і стовпців
arr2 = np.arange(4).reshape(2, 2)
print(f"\nМасив із різною кількістю рядків/стовпців:\n{arr2}")
try:
    print(f"Конкатенація з arr1 (без зміни розмірності):\n{np.concatenate((arr1, arr2), axis=1)}")
except ValueError as e:
    print(f"Помилка при конкатенації: {e}")
    arr2_reshaped = arr2.reshape(3, 2)  # Зміна розмірності
    print(f"Після зміни розмірності arr2:\n{arr2_reshaped}")
    print(f"Конкатенація:\n{np.concatenate((arr1, arr2_reshaped), axis=1)}")
    
    # Комбінації reshape для сумарної розмірності 12
    total_elements = 12
    combinations = []
    for i in range(1, total_elements + 1):
        if total_elements % i == 0:
            combinations.append((i, total_elements // i))
    print(f"\nВсі можливі комбінації reshape для масиву з 12 елементів:")
    for comb in combinations:
        reshaped = np.arange(total_elements).reshape(comb)
        print(f"Форма: {comb}\n{reshaped}\n")





При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]
При конкатенації стовпців маємо:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Масив D [1. 1. 1.] має розмірність (3,), тому може виконати операцію конкатенації з B (3, 3):
[[0.01612318 0.83580827 0.84702848 1.        ]
 [0.18512025 0.95811912 0.46156215 1.        ]
 [0.96610156 0.64682308 0.83329605 1.        ]]
Для конкатенації з C:
[[0.99184744]
 [0.78471187]
 [0.5709121 ]]
де C має розмірність = (3, 1), потрібно змінити розмірність D = (3,).
Це можна ось так:
(3, 1)
або
(3, 1)
В результаті ми можемо виконати конкатенацію:
[[0.99184744 1.        ]
 [0.78471187 1.        ]
 [0.5709121  1.        ]]
При повторенні D [1. 1. 1.] 2 рази для рядків та 3 для стовпців будемо мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]
Також можна перетворити двовимірний масив A розмірністю (3, 3) на рядок: [1 2 

# Трансформації масивів
> масии можуть бути трансформовані багатьма способами зміщюючи позиції рядкі або стопців;

> транспонація - заміна рядкі на стопці;

> функції `size` та `shape` - дозволяють визначити кількість елементів 

In [6]:
import numpy as np

# Створення масиву O
O = np.arange(6).reshape(3, 2)
O_r = O.reshape((2, 3))  # Зміна розмірності
O_f = O.flatten()  # Перетворення на рядок
O_t = O.transpose()  # Транспонування
O_fl = np.flip(O)  # Оборот по всіх осях
O_fa = np.flip(O, axis=1)  # Оборот по стовпцях

# Виведення результатів
print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")


# Створення вектора з 12 елементів
vector = np.arange(12)
print(f"Вектор: {vector}\nРозмірність: {vector.shape}, size: {vector.size}, ndim: {np.ndim(vector)}")

# Зміна розміру на матрицю 3x4
matrix = vector.reshape(3, 4)
print(f"\nМатриця 3x4:\n{matrix}")
    
# Транспонування
transposed_matrix = matrix.transpose()
print(f"\nТранспонована матриця:\n{transposed_matrix}")
    
# Обертання
flipped_matrix = np.flip(matrix)
print(f"\nОбертання матриці:\n{flipped_matrix}")
    
# Перетворення в вектор
flattened_matrix = flipped_matrix.flatten()
print(f"\nПеретворена векторна форма:\n{flattened_matrix}")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]

Вектор: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Розмірність: (12,), size: 12, ndim: 1

Матриця 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Транспонована матриця:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Обертання матриці:
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]

Перетворена векторна форма:
[11 10  9  8  7  6  5  4  3  2  1  0]
