# Статистичні операції над масивами

In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

## Генерація випадкових масивів та статистичні закони розподілу

In [2]:
C = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(f"""Масив {C.shape} можна задавати вручну:
{C}
""")

rng = np.random.default_rng()
C = rng.random((3, 4))
print(f"""Можна згенерувати випадковийтакоїж розморності {C.shape}:
{C}
""")

rng = np.random.default_rng(seed=10)
C = rng.random((3, 4))
print(f"""Для того щоб згенерований масив {C.shape} мав завжди однакові значення використовуємо параметер seed:
{C}
""")

I = rng.integers(0, 10, size=(3, 4), endpoint=True)
print(f"""Можемо оперувати цілими числами (задаючи мін і макс):
{I}
""")

Масив (3, 4) можна задавати вручну:
[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]

Можна згенерувати випадковийтакоїж розморності (3, 4):
[[0.94990485 0.28233889 0.63150558 0.93861054]
 [0.78046471 0.11019338 0.21304471 0.58614623]
 [0.18204992 0.76570187 0.38609558 0.18050311]]

Для того щоб згенерований масив (3, 4) мав завжди однакові значення використовуємо параметер seed:
[[0.95600171 0.20768181 0.82844489 0.14928212]
 [0.51280462 0.1359196  0.68903648 0.84174772]
 [0.425509   0.956926   0.82533291 0.33821531]]

Можемо оперувати цілими числами (задаючи мін і макс):
[[ 8  6 10  8]
 [10  9  1 10]
 [ 9  1 10  8]]



# Величини які характеризують множину чисел

> Математичне сподівання `mean` - сума всіх елементів поділена на кількість;

> Медіана `median` - середній елемент у відсортованому масиві (якщо таких елементи 2 то береться середнє значення);

> Дисперсія (`variance`) - міра розсіяння випадкової величини від середнього (середнє арифметичне відхилення квадратів);

> Стандартне відхилення (середнє квадратичне відхилення `std`) - ;

In [3]:
C =  np.array([1, 2, 5, 8, 9, 10]) # Для кращого розуміння розрахунків
print(f"""Працюємо з останнім масивом:
{C}

Сума всіх елементів:    {C.sum()}
Добуток всіх елементів: {C.prod()}

Мінімальний елемент:    {C.min()}
Максимальний елемент:   {C.max()}

Середнє значення:       {C.mean()}  \tте саме що {C.sum() / np.size(C)}
Медіана:                {np.median(C)}      
Дисперсія:              {C.var()}   \tте саме що {np.sum((C - C.mean())**2 / C.size)}
Відхилення:             {C.std()}   \tте саме що {np.sqrt(C.var())}

Заокруглили всі значення:
{np.round(C)}
Tа знайшли унікальні величини: {np.unique(np.round(C))}
Та порахувавли кількість унікальних значеннь: {np.unique(np.round(C), return_counts=True)[1]}
""")

Працюємо з останнім масивом:
[ 1  2  5  8  9 10]

Сума всіх елементів:    35
Добуток всіх елементів: 7200

Мінімальний елемент:    1
Максимальний елемент:   10

Середнє значення:       5.833333333333333  	те саме що 5.833333333333333
Медіана:                6.5      
Дисперсія:              11.805555555555555   	те саме що 11.805555555555555
Відхилення:             3.435921354681384   	те саме що 3.435921354681384

Заокруглили всі значення:
[ 1  2  5  8  9 10]
Tа знайшли унікальні величини: [ 1  2  5  8  9 10]
Та порахувавли кількість унікальних значеннь: [1 1 1 1 1 1]



> якщо маємо багатовимірний масив то застосовувати статистичні методи можна і до окремих рядків або стовпців, при цьому потрібно вказувати осі (`axis`) за якими буде здійснено розрахунки.

In [4]:
C = C.reshape(2,3)
print(f"""{C}

Сума елементів по стовпцях:         {C.sum(axis=0)}
Сума елементів по рядках:           {C.sum(axis=1)}

Добуток елементів по стовпцях:      {C.prod(axis=0)}
Добуток елементів по рядках:        {C.prod(axis=1)}

Мінімальний елемент по стовпцях:    {C.min(axis=0)}
Мінімальний елемент по рядках:      {C.min(axis=1)}
Максимальний елемент по стовпцях:   {C.max(axis=0)}
Максимальний елемент по рядках:     {C.max(axis=1)}

Середнє значення по стовпцях:       {C.mean(axis=0)}
Дисперсія по стовпцях:              {C.var(axis=0)}
Відхилення по стовпцях:             {C.std(axis=0)}

""")

[[ 1  2  5]
 [ 8  9 10]]

Сума елементів по стовпцях:         [ 9 11 15]
Сума елементів по рядках:           [ 8 27]

Добуток елементів по стовпцях:      [ 8 18 50]
Добуток елементів по рядках:        [ 10 720]

Мінімальний елемент по стовпцях:    [1 2 5]
Мінімальний елемент по рядках:      [1 8]
Максимальний елемент по стовпцях:   [ 8  9 10]
Максимальний елемент по рядках:     [ 5 10]

Середнє значення по стовпцях:       [4.5 5.5 7.5]
Дисперсія по стовпцях:              [12.25 12.25  6.25]
Відхилення по стовпцях:             [3.5 3.5 2.5]


