### Робота з бібліотекою Numpy
> Після встанолення бібліотеки можливо буде потрібно рестартувати ядро Python, використайте кнопку `Restart`.

In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")

In [2]:
import numpy as np

# Перелік температур
temp_values = [19.5, 19.8, 20.0, 20.3]
print(temp_values)

# Некоректне множення списку
result1 = temp_values * 4
print(f"Після множення на 4 отримуємо: {result1}")
print("Цей список просто дублюється чотири рази, адже множення списку в Python повторює його вміст, а не змінює значення елементів.")

# Правильне множення значень у списку
result1 = [value * 4 for value in temp_values]
print(f"Результат після правильного множення: {result1}")
print("Тепер кожен елемент списку було помножено на 4, оскільки використано ітерацію з обчисленням для кожного значення окремо.")

# Масив NumPy
array_temp = np.array(temp_values)
print("Створено NumPy масив із зазначених значень:", array_temp)

# Множення масиву NumPy
result2 = array_temp * 4
print("Результат множення масиву на 4:", result2)
print("У випадку з NumPy масивами операції автоматично застосовуються до кожного елемента, завдяки чому множення працює правильно.")


[19.5, 19.8, 20.0, 20.3]
Після множення на 4 отримуємо: [19.5, 19.8, 20.0, 20.3, 19.5, 19.8, 20.0, 20.3, 19.5, 19.8, 20.0, 20.3, 19.5, 19.8, 20.0, 20.3]
Цей список просто дублюється чотири рази, адже множення списку в Python повторює його вміст, а не змінює значення елементів.
Результат після правильного множення: [78.0, 79.2, 80.0, 81.2]
Тепер кожен елемент списку було помножено на 4, оскільки використано ітерацію з обчисленням для кожного значення окремо.
Створено NumPy масив із зазначених значень: [19.5 19.8 20.  20.3]
Результат множення масиву на 4: [78.  79.2 80.  81.2]
У випадку з NumPy масивами операції автоматично застосовуються до кожного елемента, завдяки чому множення працює правильно.


### Вектори, створення та робота з ними

In [3]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


#### Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [4]:
start_value = 5
vector_size = 100

# Створення масивів за допомогою range і arange
range_array = range(vector_size)
numpy_array = np.arange(vector_size)
print(f"Масив, створений через range: {list(range_array)[:5]}, і через arange: {numpy_array[:5]}")
print("Повний діапазон чисел із range:", list(range_array))
print("Повний діапазон чисел із arange:", numpy_array)

# Генерація масиву з початкового значення
numpy_array = np.arange(start_value, vector_size)
print(f"Можна вказати початкове значення генерації, перший елемент: {numpy_array[0]}")
print(f"Останній елемент у згенерованому масиві: {numpy_array[-1]}")

range_array = range(start_value, vector_size)
print("Аналогічно, використовуючи range:", list(range_array))
print("Елемент із середини діапазону (range):", list(range_array)[len(list(range_array)) // 2])

# Робота з дробовими числами
fractional_array = np.arange(10.4)
print("Результат створення масиву з дробовими значеннями:", fractional_array)

# Крок 0.5
fractional_array = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", fractional_array)

# Крок 0.08
fractional_array = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", fractional_array)
print("Майте на увазі можливі похибки через особливості чисел із плаваючою точкою.")

# Крок 0.0001
fractional_array = np.arange(0.0001, 0.001, 0.0001)
print("З кроком 0.0001:", fractional_array)

# Множення масиву на число
multiplied_array = fractional_array * 2.5
print("Після множення на 2.5:", multiplied_array)

# Піднесення до квадрату і ділення
final_result = (multiplied_array**2) / 0.4
print("Результат піднесення до квадрату та поділу на 0.4:", final_result)


Масив, створений через range: [0, 1, 2, 3, 4], і через arange: [0 1 2 3 4]
Повний діапазон чисел із range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Повний діапазон чисел із arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Можна вказати початкове значення генерації, перший елемент: 5
Останній елемент у згенерованому масиві: 99
Аналогічно, використовуючи range: [5, 6, 7, 8, 9, 10, 11,

#### Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [5]:
start_value = 5
vector_length = 100

# Генерація чисел через linspace
linspace_array = np.linspace(start_value, vector_length)
print(f"Згенеровано {len(linspace_array)} чисел у діапазоні від {linspace_array[0]} до {linspace_array[-1]}")

# Виведення кожного другого елемента з масиву
print("Кожний другий елемент з діапазону:")
for index in range(1, len(linspace_array), 2):
    print(linspace_array[index])

# Зменшення кількості елементів до 5
print("Зменшимо кількість чисел до 5:")
linspace_array = np.linspace(start_value, vector_length, 5)
print(linspace_array)

# Збільшення кількості елементів до 100, виведення перших та останніх 10
linspace_array = np.linspace(start_value, vector_length, 100)
print("Перші 10 чисел:", linspace_array[:10])
print("Останні 10 чисел:", linspace_array[-10:])

# Виключення останнього значення
print("""
Перше та останнє значення завжди входять у створений діапазон за замовчуванням. 
Це впливає на розрахунок кроку між значеннями. 
Якщо виключити останнє значення, діапазон змінюється.
""")
print("Масив без останнього значення:", np.linspace(start_value, vector_length, 5, endpoint=False))

# Автоматичне визначення кроку
_, step_with_endpoint = np.linspace(start_value, vector_length, 5, endpoint=True, retstep=True)
_, step_without_endpoint = np.linspace(start_value, vector_length, 5, endpoint=False, retstep=True)
print(f"Крок при включеному останньому значенні: {step_with_endpoint}")
print(f"Крок при виключеному останньому значенні: {step_without_endpoint}")

# Причина різних кроків
print("Кроки різняться, оскільки при включенні останнього значення діапазон розбивається на n-1 інтервалів, а при виключенні — на n.")


Згенеровано 50 чисел у діапазоні від 5.0 до 100.0
Кожний другий елемент з діапазону:
6.938775510204081
10.816326530612244
14.693877551020408
18.57142857142857
22.448979591836736
26.3265306122449
30.20408163265306
34.08163265306122
37.95918367346939
41.83673469387755
45.714285714285715
49.59183673469388
53.46938775510204
57.3469387755102
61.224489795918366
65.10204081632654
68.9795918367347
72.85714285714286
76.73469387755102
80.61224489795919
84.48979591836735
88.36734693877551
92.24489795918367
96.12244897959184
100.0
Зменшимо кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]
Перші 10 чисел: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]
Останні 10 чисел: [ 91.36363636  92.32323232  93.28282828  94.24242424  95.2020202
  96.16161616  97.12121212  98.08080808  99.04040404 100.        ]

Перше та останнє значення завжди входять у створений діапазон за замовчуванням. 
Це впливає на розрахунок кроку між зн

### Типи масивів/векторів

In [6]:
examples = {
    'Скаляр': np.array(42), 
    'Вектор Рядок': np.array([4, 8, 15]), 
    'Вектор Стовпець': np.array([[7], [14], [21]]), 
    'Матриця': np.array([[1, 3], [5, 7], [9, 11]]),
    'Багатовимірна Матриця': np.array([ [[101, 102], [103, 104]],
                                         [[201, 202], [203, 204]],
                                         [[301, 302], [303, 304]] ])
}

for key, value in examples.items():
    print(f"Розглядаємо приклад: {key}. \nЗначення масиву: \n", value)
    print(f"Тип даних ({key}): ", type(value))
    print(f"Кількість вимірів ({key}):", np.ndim(value))
    print(f"Форма ({key}): ", value.shape)
    print(f"Загальна кількість елементів ({key}): {np.size(value)}")
    print("-=-" * 10)

# Створення власних масивів
custom_vector_1 = np.array([12, 24, 36])
custom_vector_2 = np.array([[72], [144], [216]])

print("Користувацький Вектор Рядок:", custom_vector_1)
print("Розмірність:", np.ndim(custom_vector_1), ", Форма:", custom_vector_1.shape)
print("Користувацький Вектор Стовпець:\n", custom_vector_2)
print("Розмірність:", np.ndim(custom_vector_2), ", Форма:", custom_vector_2.shape)

# Пояснення розмірності та форми
print("""
Функція np.ndim використовується для визначення кількості вимірів (axes) масиву:
- Скаляр є нульовимірним.
- Вектор Рядок має 1 вимір, а Вектор Стовпець — 2 виміри, навіть якщо кількість елементів однакова.
- Матриці мають 2 виміри, а багатовимірні масиви — 3 і більше.
Форма (shape) вказує на розміри масиву у кожному вимірі.
""")


Розглядаємо приклад: Скаляр. 
Значення масиву: 
 42
Тип даних (Скаляр):  <class 'numpy.ndarray'>
Кількість вимірів (Скаляр): 0
Форма (Скаляр):  ()
Загальна кількість елементів (Скаляр): 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад: Вектор Рядок. 
Значення масиву: 
 [ 4  8 15]
Тип даних (Вектор Рядок):  <class 'numpy.ndarray'>
Кількість вимірів (Вектор Рядок): 1
Форма (Вектор Рядок):  (3,)
Загальна кількість елементів (Вектор Рядок): 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад: Вектор Стовпець. 
Значення масиву: 
 [[ 7]
 [14]
 [21]]
Тип даних (Вектор Стовпець):  <class 'numpy.ndarray'>
Кількість вимірів (Вектор Стовпець): 2
Форма (Вектор Стовпець):  (3, 1)
Загальна кількість елементів (Вектор Стовпець): 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад: Матриця. 
Значення масиву: 
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
Тип даних (Матриця):  <class 'numpy.ndarray'>
Кількість вимірів (Матриця): 2
Форма (Матриця):  (3, 2)
Загальна кількість елементів (Матриця): 6
-=--=--=--=--=--

### Багатовимірні масиви, розуміння вимірів
> Метод np.shape дозволяє зрозуміти виріми масиву і подає їх як (кількість рядків, кількість стовпців, кількість елементів).
Зверніть увагу на кількість квадратних дужок!!

In [7]:
examples = {
    '5 рядків': np.array([[10], [20], [30], [40], [50]]), 
    '5 стовпців': np.array([[11, 21, 31, 41, 51]]),
    '5 елементів у вкладеному масиві': np.array([[[12, 22, 32, 42, 52]]])
}

for description, array in examples.items():
    print(f"Для прикладу '{description}' маємо shape: \n{array.shape} \nі сам масив: \n{array}")
    print("-=-" * 10)

# Створення власних масивів
own_array_1 = np.array([100, 200, 300, 400])  # Одновимірний масив
own_array_2 = np.array([[101, 201], [301, 401], [501, 601]])  # Двовимірний масив
own_array_3 = np.array([[[102, 202]], [[302, 402]], [[502, 602]]])  # Тривимірний масив

print("Користувацький одновимірний масив:")
print("Масив:", own_array_1, ", shape:", own_array_1.shape)

print("Користувацький двовимірний масив:")
print("Масив:\n", own_array_2, ", shape:", own_array_2.shape)

print("Користувацький тривимірний масив:")
print("Масив:\n", own_array_3, ", shape:", own_array_3.shape)


Для прикладу '5 рядків' маємо shape: 
(5, 1) 
і сам масив: 
[[10]
 [20]
 [30]
 [40]
 [50]]
-=--=--=--=--=--=--=--=--=--=-
Для прикладу '5 стовпців' маємо shape: 
(1, 5) 
і сам масив: 
[[11 21 31 41 51]]
-=--=--=--=--=--=--=--=--=--=-
Для прикладу '5 елементів у вкладеному масиві' маємо shape: 
(1, 1, 5) 
і сам масив: 
[[[12 22 32 42 52]]]
-=--=--=--=--=--=--=--=--=--=-
Користувацький одновимірний масив:
Масив: [100 200 300 400] , shape: (4,)
Користувацький двовимірний масив:
Масив:
 [[101 201]
 [301 401]
 [501 601]] , shape: (3, 2)
Користувацький тривимірний масив:
Масив:
 [[[102 202]]

 [[302 402]]

 [[502 602]]] , shape: (3, 1, 2)


### Indexing and Slicing
> для доступу до елементів масиву використовуються Indexing, а якщо потрібно доступитись до декількох елементів зразу Slicing.

In [8]:
F = np.array([2, 3, 5, 7, 11, 13, 17, 19])
print(f"""Масив: {F}
Розміри: {F.shape}
Нумерація в масиві починається з 0.
Перший елемент масиву: {F[0]}
Другий: {F[1]}
Останній елемент (індекс {len(F)-1}): {F[7]}""")

print(f"""Для доступу до елементів з кінця масиву можемо використовувати від’ємні індекси.
Нумерація при цьому починається з -1.
Останній елемент: {F[-1]}
Передостанній: {F[-2]}""")

# Доступ до елементів різними способами
print("Кілька елементів за допомогою зрізу (slice):", F[3:6])  # Елементи з індексами 3, 4, 5
print("Кожен другий елемент масиву:", F[::2])  # Крок через 2 елементи
print("Елементи у зворотному порядку:", F[::-1])  # Реверс масиву


Масив: [ 2  3  5  7 11 13 17 19]
Розміри: (8,)
Нумерація в масиві починається з 0.
Перший елемент масиву: 2
Другий: 3
Останній елемент (індекс 7): 19
Для доступу до елементів з кінця масиву можемо використовувати від’ємні індекси.
Нумерація при цьому починається з -1.
Останній елемент: 19
Передостанній: 17
Кілька елементів за допомогою зрізу (slice): [ 7 11 13]
Кожен другий елемент масиву: [ 2  5 11 17]
Елементи у зворотному порядку: [19 17 13 11  7  5  3  2]


In [9]:
A = np.array([[2.5, 7.4, 6.8], 
              [0.9, -5.7, -1.2],
              [3.6, 10.1, 3.4],
              [6.5, -4.3, 4.2]])

print(f"""Масив:
{A}
Розміри: {A.shape}
Принцип індексації той самий, ТІЛЬКИ:
Якщо вказати одне значення, вибирається весь рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для вибору стовпця використовується символ ':', щоб взяти всі елементи:
    Перший стовпець: {A[:, 0]}
    Останній стовпець: {A[:, -1]}
Для доступу до конкретного елемента потрібно вказати два значення:
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

# Доступ до елементів, що лежать на діагоналі
diagonal_elements = [A[i, i] for i in range(min(A.shape))]
print("Елементи діагоналі масиву A:", diagonal_elements)

# Альтернативний спосіб за допомогою np.diagonal()
diagonal_np = np.diagonal(A)
print("Елементи діагоналі через np.diagonal():", diagonal_np)


Масив:
[[ 2.5  7.4  6.8]
 [ 0.9 -5.7 -1.2]
 [ 3.6 10.1  3.4]
 [ 6.5 -4.3  4.2]]
Розміри: (4, 3)
Принцип індексації той самий, ТІЛЬКИ:
Якщо вказати одне значення, вибирається весь рядок:
    Перший рядок: [2.5 7.4 6.8]
    Останній рядок: [ 6.5 -4.3  4.2]
Для вибору стовпця використовується символ ':', щоб взяти всі елементи:
    Перший стовпець: [2.5 0.9 3.6 6.5]
    Останній стовпець: [ 6.8 -1.2  3.4  4.2]
Для доступу до конкретного елемента потрібно вказати два значення:
    Перший елемент: 2.5 або 2.5
    Останній елемент: 4.2 або 4.2 або 4.2

Елементи діагоналі масиву A: [np.float64(2.5), np.float64(-5.7), np.float64(3.4)]
Елементи діагоналі через np.diagonal(): [ 2.5 -5.7  3.4]


> Для доступу до декількох елементів використовують Slicing. 
Принцип доступу до елементів  S[start:stop:step]. 
Елемент stop не включається у вивід.

In [10]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")

# Витягування 4 значень з кінця масиву
last_four_elements = S[-4:]
print("Останні 4 елементи масиву:", last_four_elements)


Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]

Останні 4 елементи масиву: [6 7 8 9]


> Такий самий принцип Slicing може використовуватись для багатовимірних масивів.

In [11]:
A = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Розміри: {A.shape}
Вибираємо декілька рядків: 
{A[0:2]}  # Перші два рядки
Два перші стовпці: 
{A[:, 0:2]}  # Усі рядки, але лише перші два стовпці
Два останні рядки:
{A[3:, :]}  # Рядки з індексом 3 до кінця
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}  # Нижня права частина матриці
""")

# Витягування матриці 2х2 з нижнього правого кута
lower_corner = A[-2:, -2:]
print("Матриця 2х2 з нижнього правого кута:")
print(lower_corner)

# Витягування матриці 2х2 з верхнього лівого кута
upper_corner = A[:2, :2]
print("Матриця 2х2 з верхнього лівого кута:")
print(upper_corner)


Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Розміри: (5, 5)
Вибираємо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]  # Перші два рядки
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]  # Усі рядки, але лише перші два стовпці
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]  # Рядки з індексом 3 до кінця
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]  # Нижня права частина матриці

Матриця 2х2 з нижнього правого кута:
[[44 45]
 [54 55]]
Матриця 2х2 з верхнього лівого кута:
[[11 12]
 [21 22]]


> Slicing дозволяє брати не тільки послідовні значення але із заданим кроком.

In [12]:
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен другий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент в кожному другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повністю змінити порядок елементів:
{A[::-1, ::-1]}
""")

# Приклад комбінації: кожен третій елемент із останніх двох рядків
custom_selection = A[-2:, ::3]
print("Вибрані елементи (кожен третій елемент із останніх двох рядків):")
print(custom_selection)


Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен другий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент в кожному другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повністю змінити порядок елементів:
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]

Вибрані елементи (кожен третій елемент із останніх двох рядків):
[[14 17 20]
 [21 24 27]]


> можна здійснювати вибірку елементів по умові

In [13]:
A = np.arange(50)
all_even = (A % 2 == 0)  # Умова: парні числа
complex = (A < 30) & (A / 5 < 2)  # Умова: числа менші 30 і при діленні на 5 менші 2

print(f"""Спочатку створюємо умову, за якою будемо здійснювати вибірку.
Результат умови буде True або False, наприклад:
Для {A[0]} -> {all_even[0]}, для {A[1]} -> {all_even[1]}.
Застосувавши умову пошуку парних чисел до масиву, отримаємо:
{A[all_even]}
Якщо застосувати більш складну умову з двох порівнянь:
{A[complex]}
""")

# Виведення непарних чисел
all_odd = (A % 2 != 0)  # Умова: непарні числа
print("Непарні числа з масиву:")
print(A[all_odd])


Спочатку створюємо умову, за якою будемо здійснювати вибірку.
Результат умови буде True або False, наприклад:
Для 0 -> True, для 1 -> False.
Застосувавши умову пошуку парних чисел до масиву, отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Якщо застосувати більш складну умову з двох порівнянь:
[0 1 2 3 4 5 6 7 8 9]

Непарні числа з масиву:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Функції для створення матриць: ones, zeros, identity, eye, empty

In [14]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця, в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця містить набір випадкових чисел, які залишилися в пам'яті:
{t}
""")



Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця, в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця містить набір випадкових чисел, які залишилися в пам'яті:
[0.00000000e+000 0.00000000e+000 8.34402697e-309 3.30650135e-310
 0.00000000e+000]

